############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Our Work"
url = "projects/"
weight = 2

# footer menu
[[footer]]
name = "Contact us"
url = "contact/"
weight = 1
